# Generated by Django 5.0.4 on 2024-05-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0004_remove_product_anti_counterfeit_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
